### PR TITLE
Fix subtle tabs bug

### LINKED ISSUE #1732: Update python example data for docs

### PR DESCRIPTION
**Pull request by mparke**
closes #1732
screen shot 2017-05-25 at 3 37 45 pm

### CODE REVIEW

File: docs/src/components/Example.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ import React from 'react';
 
 export default function Example(props) {
   const { example } = props;
-
+
```
Comment (na3d) [inline docs/src/components/Example.js]: whitespace?
