### PR TITLE
Fix some dns issues

### LINKED ISSUE #1279: Create and Edit  A/AAAA intelligent about IPv4 and IPv6 address
from the dropdown

### LINKED ISSUE #1289: DNS TTL: remove details from default
remove the details, `(1 day)` for example, from `default (1 day)` in TTL values. Add as `title=` attribute instead

### LINKED ISSUE #1296: DNS: SRV > update target placeholder
should be `www`

### LINKED ISSUE #1942: add TTL default to domains dropdowns

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #1296, closes #1289, closes #1942, closes #1279 
screen shot 2017-06-26 at 3 53 33 pm
screen shot 2017-06-26 at 3 53 39 pm

screen shot 2017-06-26 at 3 59 47 pm
screen shot 2017-06-26 at 3 59 52 pm

### CODE REVIEW

File: src/domains/components/EditARecord.js [hunk 1]
```diff
@@ -59,6 +53,10 @@ export default class EditARecord extends Component {
   }
 
   onChange = ({ target: { name, value } }) => this.setState({ [name]: value })
+  onIPChange = ({ target: { value } }) => {
+    const type = value.indexOf(':') !== -1 ? 'AAAA' : 'A';
```
Comment (abemassry) [inline src/domains/components/EditARecord.js]: this will vary based on what the value is:
to test edit a domain record
image
then delete the IP
image
then type a number
image
then delete that number
image
then enter a `:` and delete it
image

File: src/domains/components/EditARecord.js [hunk 2]
```diff
@@ -80,8 +78,8 @@ export default class EditARecord extends Component {
             id="ip"
             name="ip"
             value={ip}
-            placeholder="1.1.1.1"
-            onChange={this.onChange}
+            placeholder={type === 'A' ? '172.16.254.1' : '2001:0db8:85a3:0000:0000:8a2e:0370:7334'}
```
Comment (abemassry) [inline src/domains/components/EditARecord.js]: changes this
