### PR TITLE
Fix browser hang on notification show

### LINKED ISSUE #866: Rebooting a Linode and entering the notifications menu causes the browser to hang

### PR DESCRIPTION
**Pull request by briansteffens**
Closes #866

### CODE REVIEW

File: src/api/events.js [hunk 1]
```diff
@@ -9,8 +9,18 @@ export function eventAction(action) {
     await dispatch(actions.one({ ...event, [action]: true }, eventId));
 
     if (action === 'seen') {
-      Object.keys(state.api.events.events).forEach(eventId =>
-        dispatch(actions.one({ seen: true }, eventId)));
+      // Mark all events seen. Using many to avoid a dispatch per event.
+      const page = {
+        events: [],
```
Comment (eatonphil) [inline src/api/events.js]: events: state.api.events.events.reduce((unseen, event) => event.seen ? unseen : { ...event, seen: true }, []),

**Comment by eatonphil** [comment]
Nice work @briansteffens.

**Comment by eatonphil** [comment]
Heh, I wasn't too serious about the change. Still looks good.
