### PR TITLE
Fix reset rdns wording and only display when relevant

### LINKED ISSUE #1394: IPv6 Reset RDNS button should say Remove

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #1394

### CODE REVIEW

File: src/linodes/linode/networking/layouts/SummaryPage.js [hunk 1]
```diff
@@ -66,12 +66,17 @@ export class SummaryPage extends Component {
     //  elements.pop();
     // }
 
+    console.log(record.type, record.version);
```
Comment (mparke) [inline src/linodes/linode/networking/layouts/SummaryPage.js]: console.log?

Comment (eatonphil) [inline src/linodes/linode/networking/layouts/SummaryPage.js]: Done, thanks
