### PR TITLE
replace history state if zone label changes

### LINKED ISSUE #1236: Editing the primary zone in the SOA modal does not redirect to new page
The url is based on the zone's `dnszone` attribute which can change in the SOA edit modal. Editing this field should redirect after saving so the page doesn't crash.

### PR DESCRIPTION
**Pull request by mparke**
closes #1236

### CODE REVIEW

File: src/dnsmanager/layouts/ZonePage.js [hunk 1]
```diff
@@ -147,6 +154,25 @@ export class ZonePage extends Component {
     ));
   }
 
+  renderSOAEditRecord() {
+    const { dispatch } = this.props;
+    const { currentDNSZone: zone } = this.state;
+
+    dispatch(showModal(
+      'Edit SOA Record',
+      React.createElement(EditSOARecord, {
```
Comment (eatonphil) [inline src/dnsmanager/layouts/ZonePage.js]: Why create it like this?

Comment (mparke) [inline src/dnsmanager/layouts/ZonePage.js]: derp, great question, will fix here and below

**Comment by mparke** [comment]
Need to fix tests here
