### PR TITLE
Fix genThunks

### LINKED ISSUE #945: Page-worth of single event lookups are shot off during navigation of Linode page
Go directly to a Linode page while watching the Networking tab. Once the page has loaded click all tabs between Dashboard and (including) Rescue. Notice that a bunch of single GETs have been made to events. Presumably this happens [here](https://github.com/linode/manager/blob/master/src/api/genThunks.js#L119). I'm not sure why.

### PR DESCRIPTION
**Pull request by eatonphil**
It was both fetching outdated objects incorrectly and incorrectly deciding which objects were outdated. Closes #945

### CODE REVIEW

File: src/api/genThunks.js [hunk 1]
```diff
@@ -31,9 +31,10 @@ export function getStateOfSpecificResource(config, state, ids) {
   const _ids = [...ids];
   let current = root;
   let name = null;
+
   while (current !== config) {
     name = path.pop();
-    refined = refined[current.plural][_ids.shift()][name];
+    refined = refined[current.plural][+_ids.shift()][name];
```
Comment (mparke) [inline src/api/genThunks.js]: what does the `+` do here?

Comment (eatonphil) [inline src/api/genThunks.js]: Casts it to an int. I'm going to drop this though.

**Comment by eatonphil** [comment]
Thanks!
