### PR TITLE
Render correct tooltip when unit changes

### LINKED ISSUE #2287: IPv4 data labels are wrong in tooltip when changing scale

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #2287

To test:
* Change the units of the IO or Network graphs on the Linode and NodeBalancer pages, the tooltip data for a datapoint should now be accurate / take into account the units you picked.
* Make sure that the distro icon shows up on the Linode dashboard page

### CODE REVIEW

File: src/linodes/components/DistroStyle.js [hunk 1]
```diff
@@ -10,11 +10,12 @@ export default function DistroStyle(props) {
...
   }
 
+  const src = distroAssets[linode.distribution.vendor.toLowerCase()];
+
   return (
     <span className="distro-style">
       <img
-        src={distroAssets[linode.distribution.vendor]
-          ? distroAssets[linode.distribution.vendor] : '//placehold.it/50x50'}
+        src={src ? src : '//placehold.it/50x50'}
```
Comment (mparke) [inline src/linodes/components/DistroStyle.js]: can we replace this remote image url with an image served from us?

remote image src might technically be an attack vector ( whether or not we trust placehold.it )

see https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#Malformed_IMG_tags

File: src/nodebalancers/nodebalancer/layouts/DashboardPage.js [hunk 2]
```diff
@@ -114,27 +114,30 @@ export class DashboardPage extends Component {
     const { timezone, nodebalancer: { _stats: stats } } = this.props;
     const { units } = this.state;
 
+    const convertUnits = (value, unitType, fixedNumber = 0) =>
```
Comment (mparke) [inline src/nodebalancers/nodebalancer/layouts/DashboardPage.js]: copy-pasted conversion logic?
