### PR TITLE
revert the truthiness of action.emailHash

### LINKED ISSUE #315: Old session bug with email hash
Page crashes and I am stuck between not being logged out to fix the problem and not being logged in and redirect to /create/

@abemassry 

screen shot 2016-08-01 at 10 16 05 am

screen shot 2016-08-01 at 10 16 52 am

### PR DESCRIPTION
**Pull request by abemassry**
the code started out as:
```
emailHash = !!action.emailHash ? action.emailHash :
                                 md5(action.email.trim().toLowerCase());
```

then it was changed to: `if (action.email && !!emailHash) {`

the intent is if the email hash does not exist in localStorage
generate a new one, if it exists in localStorage pull it out of
there and don't generate a new one.

after we ran it we found another problem where the localStorage item
would be set to undefined instead of null.  So we changed it so that
if the action.email was undefined it would set the localStorage to null.
All of the other localStorage items are set to null incase they don't
have a value.

closes #315

### CODE REVIEW

File: src/reducers/authentication.js [hunk 1]
```diff
@@ -15,6 +15,8 @@ export default function authentication(_state = null, action) {
     case SET_TOKEN:
       if (action.email && !action.emailHash) {
         emailHash = md5(action.email.trim().toLowerCase());
+      } else {
+        emailHash = state.emailHash;
```
Comment (eatonphil) [inline src/reducers/authentication.js]: ah good

File: test/reducers/authentication.spec.js [hunk 2]
```diff
@@ -63,7 +61,6 @@ describe('authentication reducer', () => {
         scopes: [],
         username: 'me',
         email: 'me@example.org',
-        emailHash: 'cd11923284fc0f904c4732bb8f7d7e3c',
```
Comment (eatonphil) [inline test/reducers/authentication.spec.js]: Why are we dropping these?
