### PR TITLE
Fix linode status change break

### LINKED ISSUE #1423: Fix linode status change break
Linode status change never reaches completion

related: https://github.com/linode/manager/issues/1350

### PR DESCRIPTION
**Pull request by mparke**
closes #1423 

breaks polling into it's own module that is used in both notifications, and linode

### CODE REVIEW

File: src/api/apiActionReducerGenerator.js [hunk 1]
```diff
@@ -232,15 +233,17 @@ function genThunkPut(config, actions) {
...
-    const json = await response.json();
-    dispatch(actions.one(json, ...ids));
-    return json;
+  return function (resource, ...ids) {
+    return async function (dispatch, getState) {
+      const { token } = getState().authentication;
+      const response = await fetch(token, config.endpoint(...ids, ''), {
+        method: 'POST',
+        body: JSON.stringify(resource),
+      });
```
Comment (eatonphil) [inline src/api/apiActionReducerGenerator.js]: Heh, I just realized you could replace maybe half of this function with the thunkFetch helper...

File: src/api/polling.js [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+  }
+
+  function start() {
+    poll();
+  }
+
+  return Object.freeze({
+    start: start,
+    stop: stop,
+  });
```
Comment (eatonphil) [inline src/api/polling.js]: Why isn't this a class with (static?) methods?

File: src/api/apiActionReducerGenerator.js (hunk 1 above)
Comment (mparke) [inline src/api/apiActionReducerGenerator.js]: cool, might do that, I separated this to debug it. no actual change

File: src/api/polling.js (hunk 2 above)
Comment (mparke) [inline src/api/polling.js]: Tell me why it should be a class with static methods?

File: src/linodes/components/StatusDropdown.js [hunk 3]
```diff
@@ -1,22 +1,67 @@
...
+
+  onMaxPollingReached() {
+    // TODO: error state
+  }
+
+  async startLinodePolling(tempStatus = '') {
+    const { dispatch, linode } = this.props;
+
+    dispatch(actions.one({ status: tempStatus, __progress: 1 }, linode.id));
+    await new Promise(resolve => setTimeout(resolve, 0));
```
Comment (mparke) [inline src/linodes/components/StatusDropdown.js]: I should probably kill this line, was moved from another place

Comment (eatonphil) [inline src/linodes/components/StatusDropdown.js]: Ah don't be so quick on this one. There was a reason for it. Thankfully we commented as such...

File: src/api/polling.js (hunk 2 above)
Comment (eatonphil) [inline src/api/polling.js]: The static part was optional because I don't follow how you're expecting this to be used. Why shouldn't it be a class?

File: src/linodes/components/StatusDropdown.js (hunk 3 above)
Comment (mparke) [inline src/linodes/components/StatusDropdown.js]: where did we comment?

Comment (eatonphil) [inline src/linodes/components/StatusDropdown.js]: We didn't :(

File: src/api/polling.js (hunk 2 above)
Comment (mparke) [inline src/api/polling.js]: well, we appear to favor ( which I also favor ) functions in all cases we don't need to extend React's `Component`. 

I also do not want to promote the possibility of using `extend` when it is not needed. this version +1 for composition.

Yes, you can accomplish the same changes with a class, and var references on `this`, but then you also have exposed vars, which this does not, this version is +1 for encapsulation.

File: src/linodes/components/StatusDropdown.js (hunk 3 above)
Comment (mparke) [inline src/linodes/components/StatusDropdown.js]: also, by kill, i mean fix the need to do this.

File: src/api/polling.js (hunk 2 above)
Comment (eatonphil) [inline src/api/polling.js]: > well, we appear to favor ( which I also favor ) functions in all cases we don't need to extend React's Component.

We don't have anything structured class-like elsewhere. If you're going to make something like a class,I'd just make it a class.

> but then you also have exposed vars, which this does not, this version is +1 for encapsulation.

If I wanted safety I'd be doing something else. :p

Comment (mparke) [inline src/api/polling.js]: you don't need a class for this.

if I was creating a lot of these objects, i'd probably define a prototype, and still not use the class syntax.

If you can make a case for using a class here, go for it, otherwise a simple revealing module gets the job done.

Comment (mparke) [inline src/api/polling.js]: @eatonphil okay, I did think of one good use case for a class/prototype, to play my own devil's advocate:

class/prototype does make it easier to test state changes and/or mock individual functions for spying, which for functions in closure, is not possible.

**Comment by eatonphil** [comment]
No more animated progress transition?

**Comment by mparke** [comment]
Two follow ups for this:

https://github.com/linode/manager/issues/1452
https://github.com/linode/manager/issues/1453

**Comment by mparke** [comment]
one more follow up, for `provisioning`, might need to change a few things to handle this, https://github.com/linode/manager/issues/1454

**Comment by eatonphil** [comment]
Alrighty. Few things to go, but not a regression. Tested and looks good.
