### PR TITLE
Fix linode creation bugs

### LINKED ISSUE #905: Create a Linode has errors possibly related to Linode id
The create a Linode button creates a Linode but has errors before the page navigation changes to the new Linode that was just created.  This is possibly related to Linode labels in the URL.

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #905 

Few things were going wrong here aside from what was actually mentioned in 905 (could not reproduce anything that had to do with labels [undefined keys, etc]):

* All ids were being converted into integers. That does not work for datacenters / distros / plans.
* The event handlers were not handling the beginning and done states of the creation / provisioning
* Datacenters / distros / plans were being rendered with bad keys in some places which caused React warnings

### CODE REVIEW

File: src/api/gen.js [hunk 1]
```diff
@@ -32,11 +32,11 @@ function fullyQualified(resource) {
 
 const actionGenerators = {
   [ONE]: c => (resource, ...ids) =>
-    ({ type: `GEN@${fullyQualified(c)}/ONE`, resource, ids: ids.map(n => parseInt(n)) }),
+    ({ type: `GEN@${fullyQualified(c)}/ONE`, resource, ids: ids.map(n => parseInt(n) || n) }),
```
Comment (briansteffens) [inline src/api/gen.js]: If the ID is "0" this will still return "0". Can IDs ever be 0?

Comment (briansteffens) [inline src/api/gen.js]: By default MySQL auto increment starts at 1 so probably safe but maybe it can be changed.

File: src/api/gen.js [hunk 2]
```diff
@@ -84,9 +84,8 @@ export function generateDefaultStateOne(config, one) {
 }
 
 export class ReducerGenerator {
-
   static one(config, oldStateMany, action) {
-    const id = action.ids.length ? action.ids.pop() : action.resource.id;
+    const id = action.ids.length ? action.ids[action.ids.length - 1] : action.resource.id;
```
Comment (briansteffens) [inline src/api/gen.js]: I thought the pop() was there so each call to one() would pop off an ID and process that. Was that not the original intent?

Comment (eatonphil) [inline src/api/gen.js]: I don't think it matters here and I think not inducing the side-effect is clearer.

File: src/api/gen.js (hunk 1 above)
Comment (eatonphil) [inline src/api/gen.js]: "0" and 0 are actually fine for a Javascript associative array.

Comment (briansteffens) [inline src/api/gen.js]: We need IDs in int format but only if > 0?

File: src/api/linodes.js [hunk 3]
```diff
@@ -5,19 +5,23 @@ export const LINODE_STATUS_TRANSITION_RESULT = {
   booting: 'running',
   shutting_down: 'offline',
   rebooting: 'running',
+  creating: 'offline', // Technically this is "finished", but offline is more useful to us.
```
Comment (eatonphil) [inline src/api/linodes.js]: Because some UI pieces do an explicit check on offline. Finished and offline are the same thing, so we normalize it here.

File: src/linodes/create/components/Datacenter.js [hunk 4]
```diff
@@ -19,9 +13,10 @@ export default class Datacenter extends Component {
     );
   }
 
-  renderDatacenter(datacenter) {
+  renderDatacenter = (datacenter) => {
```
Comment (eatonphil) [inline src/linodes/create/components/Datacenter.js]: I saw this for the first time recently and it does work as intended. It also means we can stop having dozens of binds in the constructor so I like that aspect.

File: src/api/linodes.js (hunk 3 above)
Comment (eatonphil) [inline src/api/linodes.js]: ^^ That might be a clearer comment.

Comment (mparke) [inline src/api/linodes.js]: okay, makes sense re: finished and offline, but still confused because the key here is `creating`?

Comment (eatonphil) [inline src/api/linodes.js]: This is a table of states and what they transition to. creating was a state that had not been accounted for, so I added it to the table. Once the progress of the event is complete, the status is set to the value in this table.

File: src/linodes/create/components/Datacenter.js (hunk 4 above)
Comment (mparke) [inline src/linodes/create/components/Datacenter.js]: Ah, I had to look it up, but i see how it works now, compiles to function being defined in the constructor,

```
constructor() {
  this.renderDatacenter = () => {
  }
}
```

File: src/api/gen.js (hunk 1 above)
Comment (mparke) [inline src/api/gen.js]: What is the purpose of `|| n`? let them all be ints re: the discussion yesterday?

Comment (eatonphil) [inline src/api/gen.js]: There are pages like this that don't have integer ids.

https://api.alpha.linode.com/v4/datacenters

Comment (mparke) [inline src/api/gen.js]: ahhhh, okay, thanks for linking to that. thoughts on a more explicit check then so that fact is understood for the next person to look?

something like:

`isNan(id) ? id : parseInt(id)`

Comment (mparke) [inline src/api/gen.js]: or a comment so it's understood

Comment (eatonphil) [inline src/api/gen.js]: Sure, I'll add a comment

**Comment by eatonphil** [comment]
Ah I still had two comments to write!

**Comment by eatonphil** [comment]
Will make a continuation PR with the comments. Thanks for the merge
