### PR TITLE
stuck in finnix fix

### LINKED ISSUE #2731: Once in Finnix, users can't switch configs, if they only have one.
Expected behavior:
If the user is using the StatusDropdown to boot or reboot they should be forced into their only config if they have one. prompt to select which config they want if they have more.  They are already forced to select which config if they have more than one.

Observed behavior:
When booting and rebooting, the config is null, so it is defaulting to the last booted config, which is Finnix.

Notes:
Make sure it behaves the same on both the Linode list page and in the dashboard of a Linode.

### PR DESCRIPTION
**Pull request by na3d**
Closes #2731

### CODE REVIEW

File: src/linodes/components/StatusDropdown.js [hunk 1]
```diff
@@ -158,11 +158,14 @@ export default class StatusDropdown extends Component {
...
-    const configCount = Object.keys(linode._configs.configs).length;
+    const configs = linode._configs.configs;
+    const configCount = Object.keys(configs).length;
+
     if (configCount <= 1) {
-      dispatch(callback(linode.id));
-      dispatch(hideModal());
-      return;
+      return dispatch(dispatchOrStoreErrors.call(this, [
+        () => callback(linode.id, parseInt(Object.keys(configs)[0])),
```
Comment (displague) [inline src/linodes/components/StatusDropdown.js]: I think this would explode when there are no configs present.

**Comment by displague** [comment]
Please see https://github.com/na3d/manager/pull/17 and see if that can be used to handle a few more error cases (which I encountered while reviewing this).
