### PR TITLE
Read ID from API during POST

### LINKED ISSUE #592: Ghost linode appears when setting group and then going to linodes page without refresh

### LINKED ISSUE #631: Changing Group causes bad State
Steps to reproduce:

1. Create a new Linode (do not specify group)
1. Go to Settings tab
1. Enter Group and click Save
1. Go to Linodes page

Result:

Linode is shown twice - a solid green bar is shown where "Running" should be.

screen shot 2016-11-04 at 9 42 28 am

### PR DESCRIPTION
**Pull request by briansteffens**
Closes #592, Closes #631

### CODE REVIEW

File: src/api/gen.js [hunk 1]
```diff
@@ -84,9 +84,10 @@ function addMeta(config, item) {
 
 export function genReducer(_config) {
   function one(config, state, action) {
-    const id = action.ids[action.ids.length - 1];
-    const previous = state[config.plural][id];
+    const previousId = action.ids[action.ids.length - 1];
+    const previous = state[config.plural][previous_id];
```
Comment (eatonphil) [inline src/api/gen.js]: previousId
