### PR TITLE
Fix JUMP TO

### LINKED ISSUE #1670: Fix method jump links
Method jump links (GO TO ...) do not currently work / are not wired up. Fix this or implement something else.

### PR DESCRIPTION
**Pull request by mparke**
closes #1670 

Fixes JUMP TO links and adds ids to methods

### CODE REVIEW

File: docs/src/App.js [hunk 1]
```diff
@@ -29,11 +29,33 @@ function logPageView() {
...
+  const { hash } = window.location;
+  if (hash !== '') {
+    // Push onto callback queue so it runs after the DOM is updated,
+    // this is required when navigating from a different page so that
+    // the element is rendered on the page before trying to getElementById.
+    setTimeout(() => {
+      const id = hash.replace('#', '');
+      const element = document.getElementById(id);
+      if (element) {
+        element.scrollIntoView();
```
Comment (eatonphil) [inline docs/src/App.js]: `window.scrollBy(0, -60);` afterward?

**Comment by eatonphil** [comment]
Made a PR to your branch with minor enhancements https://github.com/mparke/manager/pull/16

File: docs/src/App.js [hunk 2]
```diff
@@ -29,11 +29,36 @@ function logPageView() {
...
+  }
+}
+
+function onRouterUpdate() {
+  logPageView();
+  hashLinkScroll();
+}
+
 export function init() {
+  setTimeout(() => hashLinkScroll(), 0);
```
Comment (eatonphil) [inline docs/src/App.js]: Ugh, missed it: `setTimeout(hashLinkScroll, 0)`
